apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-authentik-cluster
  namespace: authentik
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: postgres-authentik-secrets
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    size: 10Gi
