version: "3.7"

services:
  caddy:
    image: caddy:2.6.4_1.1.19
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./data:/data
      - ./config:/config
