providers:
  kubernetesCRD:
    allowCrossNamespace: true
ports:
  web:
    port: 80
  websecure:
    port: 443
    tls:
      enabled: true
additionalArguments:
  - --entryPoints.web.http.redirections.entryPoint.to=websecure
  - --entryPoints.web.http.redirections.entryPoint.scheme=https
  - --entryPoints.web.http.redirections.entryPoint.permanent=true
