apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-authelia-cluster
  namespace: authelia
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      secret:
        name: postgres-authelia-secrets
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    size: 10Gi
