---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: descheduler
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: DeleteFailingQbittorrent
        pluginConfig:
          - name: "DefaultEvictor"
            args:
              evictLocalStoragePods: true
          - name: "RemovePodsHavingTooManyRestarts"
            args:
              podRestartThreshold: 2
              namespaces:
                include:
                  - qbittorrent
        plugins:
          deschedule:
            enabled:
              - "RemovePodsHavingTooManyRestarts"
