apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      restartPolicy: Always
      containers:
        - name: flaresolverr
          # image: flaresolverr/flaresolverr:latest
          image: 21hsmw/flaresolverr:nodriver
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: LOG_LEVEL
              value: info
            - name: LOG_HTLM
              value: "false"
            - name: CAPTCHA_SOLVER
              value: none
          ports:
            - containerPort: 8191
