version: "2.1"
services:
  plex:
    container_name: plex
    hostname: plex
    image: plexinc/pms-docker
    environment:
      - TZ="Europe/Paris"
      # - PLEX_CLAIM="claim-uo7af8My9A5fxN9m-3g_"
      - ADVERTISE_IP="https://plex.admin.thelegend27.fr"
    volumes:
      - ./database:/config
      - /media/pictures:/pictures
      - /media/movies:/movies
      - /media/series:/series
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
