apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  source:
    chart: descheduler
    repoURL: https://kubernetes-sigs.github.io/descheduler/
    targetRevision: 0.32.2
    helm:
      valuesObject:
        kind: CronJob
        deschedulerPolicy:
          profiles:
            - name: DeleteFailingQbittorrent
              pluginConfig:
                - name: "RemoveFailedPods"
                  args:
                    namespaces:
                      include:
                        - qbittorrent
              plugins:
                deschedule:
                  enabled:
                    - "RemoveFailedPods"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler
