apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Thomas141100/homeserver.git'
      path: kubernetes/immich
      targetRevision: main
      ref: values
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: 0.9.3
      helm: 
        valueFiles:
          - $values/kubernetes/immich/values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
