apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Thomas141100/homeserver.git'
      path: kubernetes/longhorn
      targetRevision: main
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: v1.8.1
      helm:
        valuesObject:
          defaultSettings:
            replicaAutoBalance: best-effort
          preUpgradeChecker:
            jobEnabled: false
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
