apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy
  namespace: argocd
spec:
  project: default
  source:
    chart: caddy-ingress-controller
    repoURL: https://caddyserver.github.io/ingress/
    targetRevision: 1.1.0
    helm:
      parameters:
      - name: ingressController.config.email
        value: 141100thomas@gmail.com
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: caddy-system
