apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/router
    repoURL: 'https://github.com/Thomas141100/homeserver.git'
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: movies
