apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  sources:
  - repoURL: 'git@github.com:Thomas141100/homeserver.git'
    path: kubernetes/plex
    targetRevision: main
