apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Thomas141100/homeserver.git'
      path: kubernetes/loki
      targetRevision: lenovotiny
      ref: values
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.53.0
      helm:
        valueFiles:
          - $values/kubernetes/loki/values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
