# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vaultwarden
#   namespace: argocd
# spec:
#   project: default
#   source:
#     path: kubernetes/vaultwarden
#     repoURL: 'https://github.com/Thomas141100/homeserver.git'
#     targetRevision: main
#   syncPolicy:
#     automated: {}
#     syncOptions:
#       - CreateNamespace=true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: vaultwarden
