---
apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: timemachine
  labels:
    app: timemachine
spec:
  ports:
    - port: 137
      name: udp137
    - port: 138
      name: udp138
    - port: 139
      name: tcp139
    - port: 445
      name: tcp445
  type: ClusterIP
  selector:
    app: timemachine
