apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Europe/Paris"
            # - name: PLEX_CLAIM
            #   value: "claim-xxxxxxxxxxxxxxxxxxxx"
            - name: ADVERTISE_IP
              value: "http://plex.admin.thelegend27.fr"
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-series
              mountPath: /series
            - name: plex-movies
              mountPath: /movies
            - name: plex-pictures
              mountPath: /pictures
          ports:
            - containerPort: 32400
            - containerPort: 1900
            - containerPort: 32469
            - containerPort: 32410
            - containerPort: 32412
            - containerPort: 32413
            - containerPort: 32414
      volumes:
        - persistentVolumeClaim:
            claimName: plex-config
          name: plex-config
        - persistentVolumeClaim:
            claimName: plex-movies
          name: plex-movies
        - persistentVolumeClaim:
            claimName: plex-pictures
          name: plex-pictures
        - persistentVolumeClaim:
            claimName: plex-series
          name: plex-series
