apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: cert-manager
  annotations:
    gethomepage.dev/href: https://plex.admin.thelegend27.fr
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Plex
    gethomepage.dev/description: Media Server
    gethomepage.dev/icon: plex.png
    gethomepage.dev/group: Media
    gethomepage.dev/pod-selector: app=plex
    gethomepage.dev/widget.type: plex
    gethomepage.dev/widget.url: http://plex.plex:32400
    gethomepage.dev/widget.key: ""
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`plex.admin.thelegend27.fr`)
      # middlewares:
      #   - name: forwardauth-authelia
      #     namespace: traefik
      services:
        - name: plex
          namespace: plex
          port: 32400

  tls:
    secretName: wildcard-admin-thelegend27-tls
