apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Plex
    gethomepage.dev/description: Media Server
    gethomepage.dev/icon: plex.png
    gethomepage.dev/group: Media
    gethomepage.dev/pod-selector: app=plex
    gethomepage.dev/widget.type: plex
    gethomepage.dev/widget.url: http://plex.movies:32400
    gethomepage.dev/widget.key: ""
spec:
  # ingressClassName: caddy
  rules:
  - host: plex.admin.thelegend27.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              number: 32400
