services:
  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    restart: unless-stopped
    network_mode: "host"
    environment:
      # - DEBUG_LEVEL=3
      - TM_USERNAME=thelegend27
      - TM_GROUPNAME=timemachine
      - PASSWORD=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=400000000000
    # ports:
    #   - "137:137/udp"
    #   - "138:138/udp"
    #   - "139:139"
    #   - "445:445"
    volumes:
      - /mnt/timemachine:/opt/thelegend27
      - ./var-lib-samba:/var/lib/samba
      - ./var-cache-samba:/var/cache/samba
    tmpfs:
      - /run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
