version: '3.4'

services:
  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    restart: unless-stopped
    network_mode: "host"
    environment:
      - CUSTOM_AFP_CONF=false
      - LOG_LEVEL=info
      - MIMIC_MODEL=TimeCapsule6,106
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=AFPTimeMachine
      - VOLUME_SIZE_LIMIT=400000000000
    ports:
      - "548:548"
      - "636:636"
    volumes:
      - /mnt/timemachine:/opt/timemachine

