---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pictures
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/thelegend27/Images
  storageClassName: hostpath
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/media/pictures
  storageClassName: hostpath
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
