apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingress
  namespace: cert-manager
  annotations:
    gethomepage.dev/href: https://prowlarr.admin.thelegend27.fr
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Prowlarr
    gethomepage.dev/description: Indexer
    gethomepage.dev/icon: prowlarr.png
    gethomepage.dev/group: Media Management
    gethomepage.dev/pod-selector: app=prowlarr
    gethomepage.dev/widget.type: prowlarr
    gethomepage.dev/widget.url: http://prowlarr.movies:9696
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PROWLARR_TOKEN}}"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`prowlarr.admin.thelegend27.fr`)
      # middlewares:
      #   - name: forwardauth-authelia
      #     namespace: traefik
      services:
        - name: prowlarr
          namespace: movies
          port: 9696

  tls:
    secretName: wildcard-admin-thelegend27-tls
