apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingress
  namespace: cert-manager
  annotations:
    gethomepage.dev/href: https://radarr.admin.thelegend27.fr
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Radarr
    gethomepage.dev/description: Movies
    gethomepage.dev/icon: radarr.png
    gethomepage.dev/group: Media Management
    gethomepage.dev/pod-selector: app=radarr
    gethomepage.dev/widget.type: radarr
    gethomepage.dev/widget.url: radarr.movies:7878
    gethomepage.dev/widget.key: ""
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.admin.thelegend27.fr`)
      # middlewares:
      #   - name: forwardauth-authelia
      #     namespace: traefik
      services:
        - name: radarr
          namespace: movies
          port: 7878

  tls:
    secretName: wildcard-admin-thelegend27-tls
