apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thelegend27-fr-certificate
  namespace: cert-manager
spec:
  secretName: thelegend27-fr-tls
  issuerRef:
    name: cloudflare-issuer
  commonName: thelegend27.fr
  dnsNames:
  - thelegend27.fr
  - admin.thelegend27.fr
