apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Media
    - Media Management
    - Network:
      - Speedtest:
          icon: speedtest-tracker.png
          href: https://speedtest.admin.thelegend27.fr
          server: my-docker
          container: speedtest-tracker
          widget:
              type: speedtest
              url: http://speedtest-tracker:80
      - Router:
          icon: watchyourlan.png
          href: https://router.admin.thelegend27.fr
          description: Router
  widgets.yaml: |
    - logo:
        icon: /icons/icons/logo-192x192.png

    - greeting:
        text_size: xl
        text: Ratio

    - resources:
        label: System
        cpu: true
        memory: true

    # - resources:
    #     label: Root
    #     disk:
    #       - /

    - resources:
        label: Media
        disk:
          - /mnt/media

    - resources:
        label: TimeMachine
        disk:
          - /mnt/timemachine

    - search:
        provider: google
        target: _blank

  docker.yaml: ""
