---
services:
  homer:
    image: b4bz/homer
    restart: unless-stopped
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 8080:8080
    environment:
      - INIT_ASSETS=1 # default
