apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress
  namespace: movies
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarr.admin.thelegend27.fr`)
      # middlewares:
      #   - name: authentik
      #     namespace: authentik
      services:
        - name: sonarr
          port: 8989

