apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: movies
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Sonarr
    gethomepage.dev/description: TV Shows
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/group: Media Management
    gethomepage.dev/pod-selector: app=sonarr
    gethomepage.dev/widget.type: sonarr
    gethomepage.dev/widget.url: http://sonarr.movies:8989
    gethomepage.dev/widget.key: ""
spec:
  # ingressClassName: caddy
  rules:
  - host: sonarr.admin.thelegend27.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
