apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress
  namespace: cert-manager
  annotations:
    gethomepage.dev/href: https://sonarr.admin.thelegend27.fr
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Sonarr
    gethomepage.dev/description: TV Shows
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/group: Media Management
    gethomepage.dev/pod-selector: app=sonarr
    gethomepage.dev/widget.type: sonarr
    gethomepage.dev/widget.url: http://sonarr.movies:8989
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SONARR_TOKEN}}"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarr.admin.thelegend27.fr`)
      # middlewares:
      #   - name: forwardauth-authelia
      #     namespace: traefik
      services:
        - name: sonarr
          namespace: movies
          port: 8989

  tls:
    secretName: wildcard-admin-thelegend27-tls
