apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-service-monitor
  namespace: qbittorrent
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: qbittorrent
  endpoints:
    - interval: 30s
      port: metrics
