apiVersion: batch/v1
kind: CronJob
metadata:
  name: rollout-qbittorrent
  namespace: qbittorrent
spec:
  schedule: "* */8 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rollout-qbittorrent
          restartPolicy: Never
          containers:
            - name: rollout-qbittorrent
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              args:
                - rollout
                - restart
                - -n
                - qbittorrent
                - deployment/qbittorrent-wireguard
      backoffLimit: 0  
      parallelism: 1
      completions: 1
