apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-qbittorrent
  namespace: qbittorrent
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
