apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgvectors-immich
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14-v0.3.0
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - ALTER SYSTEM SET search_path TO "immich", public, vectors;
        - ALTER SCHEMA vectors OWNER TO immich;
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    size: 10Gi
  postgresql:
    shared_preload_libraries: # load pgvecto.rs shared library
      - 'vectors.so'
