apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: photoprism-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-database
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: photoprism-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pictures
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: photoprism-pictures
